version: '3'

services:
  broker-local:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "userRabbit"
      RABBITMQ_DEFAULT_PASS: "P@ssw0rd"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mensageria

networks: 
    mensageria:
      driver: bridge